In [3]:
import numpy as np

### Generate datasets

In [17]:
x1 = np.random.uniform(low = 0.0, high = 1.0 , size = 100)

print(x1.shape)
x1[0:10]

(100,)


array([0.18313219, 0.73895493, 0.50483253, 0.86348786, 0.12624929,
       0.3245654 , 0.15560464, 0.93312958, 0.39739425, 0.10225693])

In [18]:
x2 = np.random.uniform(low = 0.0, high = 1.0 , size = 100)

print(x2.shape)
x2[0:10]

(100,)


array([0.70030247, 0.78610536, 0.11724359, 0.78546615, 0.64490163,
       0.97342431, 0.24505708, 0.63364183, 0.08410265, 0.3509779 ])

In [24]:
y = 0.3 * x1 + 0.5 * x2 + 0.1

print(y.shape)
y[0:10]

(100,)


array([0.50509089, 0.71473916, 0.31007156, 0.75177943, 0.4603256 ,
       0.68408178, 0.26920993, 0.69675979, 0.2612696 , 0.30616603])

### Random search

In [25]:
num_epoch = 1000

best_error = np.inf
best_epoch = None
best_w1 = None
best_w2 = None
best_b = None

for epoch in range(num_epoch):
    w1 = np.random.uniform(low = -1.0, high = +1.0)
    w2 = np.random.uniform(low = -1.0, high = +1.0)
    b = np.random.uniform(low = -1.0, high = +1.0)
    
    y_predict = w1 * x + w2 * x2 + b
    
    error = np.abs(y_predict - y).mean()
    
    if error < best_error:
        best_error = error
        best_epoch = epoch
        best_w1 = w1
        best_w2 = w2
        best_b = b
        
        print(f"{epoch:2} w1 = {w1:.6f} w2 = {w2:.6f} b = {b:.6f} error = {error:.6f}")

print("----" * 10)
print(f"{best_epoch:2} w1 = {best_w1:.6f} w2 = {best_w2:.6f} b = {best_b:.6f} error = {best_error:.6f}")


 0 w1 = 0.823162 w2 = -0.626062 b = -0.441116 error = 0.810567
 2 w1 = -0.708193 w2 = 0.459384 b = 0.532676 error = 0.225584
 5 w1 = -0.492286 w2 = 0.359567 b = 0.605299 error = 0.153891
55 w1 = 0.177458 w2 = 0.633554 b = 0.191200 error = 0.114870
229 w1 = 0.408264 w2 = 0.401775 b = 0.140617 error = 0.114384
277 w1 = 0.054200 w2 = 0.849213 b = 0.011479 error = 0.113025
280 w1 = 0.281138 w2 = 0.366519 b = 0.218495 error = 0.094422
533 w1 = -0.105988 w2 = 0.477294 b = 0.359102 error = 0.083777
----------------------------------------
533 w1 = -0.105988 w2 = 0.477294 b = 0.359102 error = 0.083777


In [22]:
num_epoch = 100
h = 0.1

w = np.random.uniform(low = -1.0, high = +1.0)

for epoch in range(num_epoch):
    y_predict = w * x
    current_error = np.abs(y_predict - y).mean()
    
    y_predict = (w + h) * x
    h_plus_error = np.abs(y_predict - y).mean()
    
    
    if h_plus_error < current_error:
        w = w + h 
        print(f"{epoch:2} w = {w:.6f} error = {error:.6f}")
        continue
    
    y_predict = (w - h) * x
    h_minus_error = np.abs(y_predict - y).mean()
    
    
    if h_minus_error < current_error:
        w = w - h  
        print(f"{epoch:2} w1 = {w1:.6f} w2 = {w2:.6f} error = {error:.6f}")
        continue
        
print("----" * 10)
print(f"{epoch:2} w1 = {w1:.6f} w2 = {w2:.6f} error = {error:.6f}")


 0 w1 = -0.011887 w2 = 0.459184 error = 0.173622
----------------------------------------
99 w1 = -0.011887 w2 = 0.459184 error = 0.173622


### Gradiant decent

In [30]:
num_epoch = 100
learning_rate = 1.2

w1 = np.random.uniform(low = -1.0, high = +1.0)
w2 = np.random.uniform(low = -1.0, high = +1.0)
b = np.random.uniform(low = -1.0, high = +1.0)

for epoch in range(num_epoch):
    y_predict = w1 * x1 + w2 * x2 + b
     
    error = np.abs(y_predict - y).mean()
    if error < 0.005:
        break
        
    w1 = w1 - learning_rate * ((y_predict - y) * x1).mean()
    w2 = w2 - learning_rate * ((y_predict - y) * x2).mean()
    b = b - learning_rate * (y_predict - y).mean()
      
    if epoch % 10 == 0:
        print(f"{epoch:2} w1 = {w1:.6f} w2 = {w2:.6f} b = {b:.6f} error = {error:.6f}")
        
print("----" * 10)
print(f"{epoch:2} w1 = {w1:.6f} w2 = {w2:.6f} b = {b:.6f} error = {error:.6f}")

 0 w1 = 0.328717 w2 = 0.095190 b = -0.277362 error = 0.698520
10 w1 = 0.365576 w2 = 0.406507 b = 0.049947 error = 0.078622
20 w1 = 0.333185 w2 = 0.474366 b = 0.088826 error = 0.013053
----------------------------------------
29 w1 = 0.317479 w2 = 0.490720 b = 0.094499 error = 0.004542
